merchex/urls.py
from django.contrib import admin
from django.urls import path

from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("bands/", views.band_list, name = "band-list"),
    path("bands/<int:band_id>/", views.band_detail, name = "band-detail"),
    path("bands/add/", views.band_create, name = "band-create"),
    path("bands/<int:band_id>/change/", views.band_update, name = "band-update"),
    path("bands/<int:band_id>/delete/", views.band_delete, name = "band-delete"),

    path("listings/", views.listing_list, name = "listing-list"),
    path("listings/<int:listing_id>/", views.listing_detail, name = "listing-detail"),
    path("listings/add/", views.listing_create, name = "listing-create"),
    path("listings/<int:listing_id>/change/", views.listing_update, name = "listing-update"),
    path("listings/<int:listing_id>/delete/", views.listing_delete, name = "listing-delete"),

    path("contact-us/", views.contact, name = "contact-form"),
    path("email-sent/", views.email_sent, name = "email-sent"),

    path("about-us/", views.about, name = "about"),
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime


class Band(models.Model):

    class Genre(models.TextChoices):
        ALTERNATIVE_ROCK = 'AR'
        HEAVY_METAL = 'HM'
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(datetime.now().year)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    """
    To display the band's name directly in the Django Admin object list
    (not required if it has been added in a ModelAdmin).

    Or when selecting it as a foreign key in the Django Admin
    (required if we don't want to see something like
    "Band object (id_number)").
    """
    def __str__(self):
        return f"{self.name}"


class Listing(models.Model):

    class Type(models.TextChoices):
        RECORDS = "R"
        CLOTHING = "C"
        POSTERS = "P"
        MISCELLANEOUS = "M"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, blank=True, validators=[MinValueValidator(1900), MaxValueValidator(datetime.now().year)])
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    """
    To display the listing's title directly in the Django Admin object list
    (not required if it has been added in a ModelAdmin).

    Or when selecting it as a foreign key in the Django Admin
    (required if we don't want to see something like
    "Listing object (id_number)").
    """
    def __str__(self):
        return f"{self.title}"

listings/forms.py
from django import forms

from listings.models import Band, Listing


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ["active", "official_homepage"]


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ["sold"]


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

listings/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail

from listings.forms import ContactUsForm, BandForm, ListingForm
from listings.models import Band, Listing


def band_list(request):
    bands = Band.objects.all()
    return render(request, "listings/band_list.html", {"bands": bands})


def band_detail(request, band_id):
    band = Band.objects.get(id = band_id)
    return render(request, "listings/band_detail.html", {"band": band})


def band_create(request):

    if request.method == 'POST':
        # Create an instance of our form and populate it with the POST data
        form = BandForm(request.POST)

        if form.is_valid():
            # Create a new "Band", save it to the database, and redirects to the detail page of the band we just created
            band = form.save()
            return redirect("band-detail", band.id)
        
        # If the form is not valid, we let the execution continue down to the return below and display the form again (with errors)

    else:
        # This must be a GET request, so create an empty form
        form = BandForm()

    return render(request, "listings/band_create.html", {"form" : form})


def band_update(request, band_id):
    band = Band.objects.get(id = band_id)

    if request.method == 'POST':
        # Pre-fill the form with new data and with data from the Band object retrieved from the database
        form = BandForm(request.POST, instance = band)

        if form.is_valid():
            # Update the existing band in the database and redirect to the detail page of the band we just updated
            form.save()
            return redirect("band-detail", band.id)
    else:
        # Pre-fill the form with data from the Band object retrieved from the database
        form = BandForm(instance = band)

    return render(request, "listings/band_update.html", {"form" : form})


def band_delete(request, band_id):
    band = Band.objects.get(id = band_id)

    if request.method == 'POST':
        band.delete()
        return redirect("band-list")

    return render(request, "listings/band_delete.html", {"band" : band})


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, "listings/listing_list.html", {"listings": listings})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id = listing_id)
    return render(request, "listings/listing_detail.html", {"listing": listing})


def listing_create(request):
    
    if request.method == 'POST':
        # Create an instance of our form and populate it with the POST data
        form = ListingForm(request.POST)

        if form.is_valid():
            # Create a new "Listing", save it to the database, and redirects to the detail page of the listing we just created
            listing = form.save()
            return redirect("listing-detail", listing.id)
        
        # If the form is not valid, we let the execution continue down to the return below and display the form again (with errors)

    else:
        # This must be a GET request, so create an empty form
        form = ListingForm()
    
    return render(request, "listings/listing_create.html", {"form" : form})


def listing_update(request, listing_id):
    listing = Listing.objects.get(id = listing_id)

    if request.method == 'POST':
        # Pre-fill the form with new data and with data from the Listing object retrieved from the database
        form = ListingForm(request.POST, instance = listing)

        if form.is_valid():
            # Update the existing listing in the database and redirect to the detail page of the listing we just updated
            form.save()
            return redirect("listing-detail", listing.id)
    else:
        # Pre-fill the form with data from the Listing object retrieved from the database
        form = ListingForm(instance = listing)

    return render(request, "listings/listing_update.html", {"form" : form})


def listing_delete(request, listing_id):
    listing = Listing.objects.get(id = listing_id)

    if request.method == 'POST':
        listing.delete()
        return redirect("listing-list")

    return render(request, "listings/listing_delete.html", {"listing" : listing})


def contact(request):

    if request.method == "POST":
        # Create an instance of our form and populate it with the POST data
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject = f"Message from {form.cleaned_data["name"] or "anonymous"} via MerchEx Contact Us form",
                message = form.cleaned_data["message"],
                from_email = form.cleaned_data["email"],
                recipient_list = ["admin@merchex.xyz"],
            )

            return redirect("email-sent")

        # If the form is not valid, we let the execution continue down to the return below and display the form again (with errors)

    else:
        # This must be a GET request, so create an empty form
        form = ContactUsForm()
    
    return render(request, "listings/contact.html", {"form" : form})


def email_sent(request):
    return render(request, "listings/email_sent.html")


def about(request):
    return render(request, "listings/about.html")

listings/templates/listings/band_create.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Create a new band</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>

{% endblock %}

listings/templates/listings/band_delete.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Delete the band</h1>

<p>Are you sure you want to delete the band: {{ band.name }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock %}

listings/templates/listings/band_detail.html
{% extends "listings/base.html" %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre: {{ band.get_genre_display }}</li>
    <li>Year of formation: {{ band.year_formed }}</li>
    <li>Active: {{ band.active | yesno }}</li>

    {% if band.official_homepage %}
    <li>
        <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a>
    </li>
    {% endif %}

    {% for listing in band.listing_set.all %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
    </li>
    {% endfor %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Edit this band</a>

- <a href="{% url 'band-delete' band.id %}">Delete this band</a>

- <a href="{% url 'band-list' %}">Back to the list of bands</a>

{% endblock %}

listings/templates/listings/band_list.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Bands</h1>

<a href="{% url 'band-create' %}">Create a new band</a>

<ul>
    {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[Edit]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

listings/templates/listings/band_update.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Update the band</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Apply the changes">
</form>

{% endblock %}

listings/templates/listings/base.html
{% load static %}

<html>

    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>

    <body>

        <nav>
            <a href="{% url 'band-list' %}">Bands</a>
            <a href="{% url 'listing-list' %}">Listings</a>
            <a href="{% url 'contact-form' %}">Contact us</a>
            <a href="{% url 'about' %}">About us</a>
        </nav>

        {% block content %}{% endblock %}

    </body>

</html>

listings/templates/listings/contact.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Contact us</h1>

<p>We are here to help you!</p>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>

{% endblock %}

listings/templates/listings/email_sent.html
{% extends "listings/base.html" %}

{% block content %}

<p>Your email has been sent successfully!</p>

{% endblock %}

listings/templates/listings/listing_create.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Create a new listing</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>

{% endblock %}

listings/templates/listings/listing_delete.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Delete the listing</h1>

<p>Are you sure you want to delete the listing: {{ listing.title }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

{% endblock %}

listings/templates/listings/listing_detail.html
{% extends "listings/base.html" %}

{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
    <li>Type: {{ listing.get_type_display }}</li>

    {% if listing.year %}
    <li>Year of the item: {{ listing.year }}</li>
    {% endif %}

    <li>Sold: {{ listing.sold | yesno }}</li>
</ul>

<p>{{ listing.description }}</p>

<a href="{% url 'listing-update' listing.id %}">Edit this listing</a>

- <a href="{% url 'listing-delete' listing.id %}">Delete this listing</a>

- <a href="{% url 'listing-list' %}">Back to the list of listings</a>

{% endblock %}

listings/templates/listings/listing_list.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Listings</h1>

<a href="{% url 'listing-create' %}">Create a new listing</a>

<ul>
    {% for listing in listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[Edit]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

listings/templates/listings/listing_update.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Update the listing</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Apply the changes">
</form>

{% endblock %}

listings/templates/listings/listings.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Listings:</h1>

<ul>
    {% for listing in listings %}
    <li>
        {{listing.title}}
    </li>
    {% endfor %}
</ul>

{% endblock %}